### PR TITLE
Make it again possible to build the plugin inside OpenCPN source tree

### PR DESCRIPTION
**Pull request by nohal**

### CODE REVIEW

**Comment by rgleason** [comment]
Pavel is this something that should be in my branch? I've been working on this plugin.  Delatbabel's is a bit behind at this point.

**Comment by nohal** [comment]
Rick...
I got totally lost in what is the upstream here. Is it this repository? Or your fork? Are you the maintainer? Or @ptulp ? Or @delatbabel ?
These pull requests fix stuff, so they should be everywhere where applicable.

**Comment by rgleason** [comment]
Currently I am the maintainer. Sorry about that, but Peter Tulp is around but not programming for now. He has been maintaining for about 3-4 years, and I guess I am now.  Right now the most current version is  the master-updateFE branch.

https://github.com/rgleason/LogbookKonni_pi/tree/master-updateFE

I was about to make a PR too opencpn/plugins  but will hold off.
The frontend has just been updated to v1.0.64 from Jon's testplugin_pi.

I would like to get your changes for colors into the plugins too.
Also I have tried to update wxWidgets code which is thoroughly antiquated  but when I ran wxFormbuilder 3.9.0 from 2018 which appears to be the most current, logbook kind of fell apart on me. I had to go back.

The most recent deployments (v1.4.13.31)  are here in the logbook-beta repository.  https://cloudsmith.io/~opencpn/repos/logbookkonni-beta/packages/

Thanks

**Comment by nohal** [comment]
Rick...

Sorry, this is impossible to follow. If you are the maintainer now, please organize it in a way where the state of the things is clear. I am not very interested in all these details - all I need to know is what is the master against which I have to work on the fixes.

**Comment by rgleason** [comment]
Right now it have checked out and pushed to my remote  branch "master-updateFE" and that is ahead of  "master" branch.  I have now merged those changes in to "[master](https://github.com/rgleason/LogbookKonni_pi)" if that will help.    I have one small niggling path issue to fix, the user writeable data directory is showing up as  logbookdata in some OS.

**Comment by rgleason** [comment]
Pavel. I have no idea what you are talking about.

` If you are the maintainer now, please organize it in a way where the state of the things is clear. I am not very interested in all these details - all I need to know is what is the master against which I have to work on the fixes.`

Just how is this done?  There is no mechanism for this.

Actually, you should have submitted that to Jon Gough's test_plugin so that if the change is appropriate all of the Frontend2 plugins will be eventually changed. 

Evidently you don't follow these things.

**Comment by nohal** [comment]
Rick, this PR is closed, done.
But if you need to talk to me here: No, I do not follow these things, I have touched this very plugin and it did not build in the OpenCPN tree, which sucks when you need to debug it, so I fixed it. That's all.

**Comment by rgleason** [comment]
Just how is this supposed to be done?
"please organize it in a way where the state of the things is clear."

Please explain.

**Comment by rgleason** [comment]
Well if  not building plugins inside Opencpn sucks, then you'd best advise Jon Gough because a lot of plugins use testplugin and I am not going to add these changes until he adds them to testplugin, so Logbook will continue to suck as you put it.

**Comment by jongough** [comment]
I am not sure what the issue is. I build the plugins and just copy the lib file to the correct location in OCPN then debug. As long as the debugger can find the source code (I use KDevelop and it can) there is no problem. 

To get the current suite of plugins working you need to generate an Plugin Manager installable the use Plugin Manager to 'install' it the first time. This ensures that all the associated files end up in the correct locations depending on how you are running OCPN. Once this is done there is only the manual copy step (KDevelop will not copy the lib file to different locations if required at the end of the build).

Frontend2 can build locally, in the cloud or simulate the cloud locally so installation testing as well as run time testing can be done.

**Comment by nohal** [comment]
I want to create a single symlink once and then just trigger the "Build and run" action in my IDE (Xcode most of the time) and be all done. That is impossible if a plugin embedded in my source tree references global cmake variables like `CMAKE_SURCE_DIR`, trivially fixed by referencing `PROJECT_SOURCE_DIR` instead, which does not break anything on your workflow and fixes mine.
I do not need to generate any installables or copy anything anywhere for what I need to do.

**Comment by rgleason** [comment]
You answer Jon's question but not mine.  Am I to assume you were thrashing?

```
Just how is this supposed to be done?
"please organize it in a way where the state of the things is clear."

Please explain.
```

**Comment by nohal** [comment]
Rick...

I am afraid that if you continue, I will be gone from here (and probably also any other discussion where you appear behaving like this) for good. If you wonder why, I really do not feel any obligation to invest my precious free time in discussions at this level and totally diverging from the scope of my interest and the original purpose of the place where you start them.

If your fork of this project is the current upstream, there should be somewhere an indication of it being so. (If your fork of this repo is the current upstream and you are the maintainer of this plugin, I really do not understand why my PRs were merged here in less than a day from it's creation by @ptulp)
That somewhere where the state of things is described usually is a README file in the default branch of that project.

It is usually the case that the dead unmaintained projects are somehow marked so. Usually in the README in the defaut branch of that dead unmaintained project or at least somewhere in the README of the active maintained project that replaced it.

It is usually the case that the master codebase is in the default branch of a project on Github.

Just a note: That you fork something on Github does not make it yours and does not give you the maintainership rights (and "obligations"). Actually it is normal that once you finish your atomic contribution, you submit it to the upstream you forked in a form of a pull requested where the maintainer merges it, exactly as I did here and it worked perfectly.

And one suggestion I already gave you many times and you keep ignoring: Please, really please, try to focus on a finite number of subjects and improve on them, you really don't have to be absolutely everywhere all the time.

**Comment by jongough** [comment]
Just to be fair. There is a change in the way that OCPN works and how plugins are to be delivered. Plugins will be installed on OCPN using Plugin Manager which will download zip files from the cloud that match the currently running version of OCPN. Plugin Manager will install the plugin for the user without the need for elevated privileges. The builds for creating the zip files is automatic in the cloud and is done on pull acceptance, tag creation and merge into the master branch.

To say the least this is quite a change to the build and deploy system. It is taking time to roll out the changes to all plugins and Rick is doing much of the hard work updating plugins to be compatible. To do this requires a fork of the main repository and considerable effort to make the changes, check the builds and test the resulting plugins. None of this is a 'quick' change. 

Your push of the change you want is based on an out of date version of the build process. We are in the middle of getting the newer version working for this plugin, but there is no point pushing a non-working version. Your change is the first I have heard of wanting to do a build inside the OCPN source tree. All the builds that are done in the cloud are done in isolation. All the builds I do are in a similar vein as that is needed for testing the installation process. I do do debugging of OCPN and plugins but don't do the builds in the OCPN source tree either on Linux or Windows. That is not to say it shouldn't happen, but this is my first inkling that it was needed.

I am trying to understand if your change will work with the new 'libs' process that is having to be introduced for plugins where plugins have to build and statically link all libs they need (a limitation imposed by Plugin Manager which I have no control over). So some testing is needed to see if your requirement and change can be incorporated into the whole build structure. We have managed this for OpenSUSE stuff where git cannot be used, so there is no reason this could not work. It just needs testing.

**Comment by nohal** [comment]
@jongough, in your workflow `CMAKE_SOURCE_DIR == PROJECT_SOURCE_DIR`. There is no other change but replacing `CMAKE_SOURCE_DIR` with `PROJECT_SOURCE_DIR` in this pull request. I highly doubt anything will change on that in the new version of the worflow you work on.

Still I have a problem with continuing the unrelated and IMHO irrelevant to my change discussion here - this PR was opened against this codebase, is merged and closed.
And believe me, it was opened after looking at all the forks I am aware of, including Rick's, and trying to figure out which one is the current upstream. So either I am not bright enough to understand the advanced logic behind or it is not clear. Either way, I think this PR should be left alone as merged and concluded.

**Comment by jongough** [comment]
The problem will come when the updated version that Rick is working on is applied as it will backout the change you have made. I have made the change you did but to the frontend2 codebase and am now trying builds and deploys to see if it still works. 

From my reading it would appear that you build OCPN and have it start the build for LogbookKonni such that the CMAKE_SOURE_DIR actually points to OCPN and not the root of LogbookKonni. Is that the issue?

**Comment by nohal** [comment]
I simply have this plugin, and many others I work on occasisonaly, in the plugin subfolder of the OpenCPN source tree. If you use `CMAKE_SOURCE_DIR`, it of course points to the root of the OpenCPN source tree, so everything you try to resolve based on that, like paths to your file templates, is wrong, which results in the `cmake ..` not working at all and makes it impossible to even generate the makefiles or project files to do the build.

I really do not understand what problem with backing out the change you talk about. If you tell me where I should commit this fix to the upstream of all your and Rick's effort, I of course will do it and sincerelly hope that way it will somehow make it also to the stuff Rick works on. But again, please, guys, try to leave this merged and closed PR to this project alone, we are totally out of scope.

**Comment by jongough** [comment]
I am making the change in testplugin_pi which is where I am developing frontend2. We are currently up to version 1.0.165.0 . 

The idea behind frontend2 is there are the basic cmake files and cloud build files that do all the work your stuff did and integrates with the cloud build environments. These basic files do not contain any "plugin" specific information and are not touched by a developer. There are other cmake files that contain extra configurations that are specific to a plugin and along with CMakeLists.txt is where the developer makes the change.

This allows new environments to be added easily as the plugin developer just needs to copy the frontend2 files over the ones in their repository and it should add what is needed. I will add some comments to the frontend2 files to identify them as such and ask people to submit pull requests against testplugin_pi to get them integrated.

**Comment by rgleason** [comment]
Thank you Jon and Pavel, for the intelligent and useful very discussion which I hope will be added in some edited form into the Developer's Manual, because it is needed.

Additionally Pavel, you are right, I should have edited the readme and  first page of the recently added documentation files to show the maintenance repository, as I have done for other plugins as I work on them, but I don't have enough time to do all of this at once.  So sorry to have mislead you and wasted your time.

**Pull request merged**
